routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UsuarioController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

// Route::resource('usuarios', UsuarioController::class);
Route::resource('usuarios', 'UsuarioController');

app/Models/Region.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Region extends Model
{
    use HasFactory;

    protected $table = "region";
    public $timestamps =  true;

    protected $fillable = [
      'nombre',
    ];
}

app/Models/Usuario.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Region;

class Usuario extends Model
{
    use HasFactory;

    protected $table = 'usuario';
    public $timestamps = true;

    protected $fillable = [
      'rut',
      'nombre',
      'apellido',
      'correo',
      'id_region'
    ];

    public function region(){
      return $this->belongsTo(Region::class,'id_region');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/UsuarioController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Usuario;
use App\Models\Region;
use App\Http\Requests\UsuarioRequest;

class UsuarioController extends Controller
{
    //
    public function index(){
      $usuarios= Usuario::get();
      // return $usuarios;
      return view('usuarios.index',compact('usuarios'));
    }

    public function create(){
      $regiones = Region::get();
      // return $regiones;
      return view('usuarios.create',compact('regiones'));
    }

    public function store(Request $request){
      try {
        $u = new Usuario();
        $u->rut = $request->input('rut');
        $u->nombre = $request->input('nombre');
        $u->apellido = $request->input('apellido');
        $u->correo = $request->input('correo');
        $u->id_region = $request->input('region');
        $u->save();
        return redirect()->route('usuarios.create')->with('success', 'Usuario Creado Exitosamente');
      } catch (\Throwable $th) {
        return $th;
        return back()->with('danger','ERROR! El Usuario no se pudo agregar');
      }
    }

    public function show($id){
      $regiones = Region::get();
      $usuario = Usuario::findOrFail($id);
      return view('usuarios.show', compact('usuario','regiones'));
    }

    public function edit($id){
      $regiones = Region::get();
      $usuario = Usuario::findOrFail($id);
      return view('usuarios.edit', compact('usuario','regiones'));
    }

    public function update(Request $request, $id){
      try {
        $u = Usuario::findOrFail($id);
        $u->nombre = $request->input('nombre');
        $u->apellido = $request->input('apellido');
        $u->correo = $request->input('correo');
        $u->id_region = $request->input('region');
        $u->update();
        return back()->with('success','Felicidades, El Usuario se actualizo exitosamente');
      } catch (\Throwable $th) {
        return $th;
        return back()->with('danger','ERROR! El Usuario no se pudo actualizar');
      }
    }

    public function destroy($id){
      $usuario = Usuario::findOrFail($id);
      $usuario->delete();
      return redirect()->route('usuarios.index')->with('success', 'Usuario Eliminado Exitosamente');
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Sistema Compras-Ventas con Laravel y Vue Js- webtraining-it.com">
    <meta name="keyword" content="Sistema Compras-Ventas con Laravel y Vue Js">
    <title>Proyecto</title>
    <link href="{{ asset('css/font-awesome.min.css') }}" rel="stylesheet">
    <link href="{{ asset('css/simple-line-icons.min.css') }}" rel="stylesheet">
    <link href="{{ asset('css/style.css') }}" rel="stylesheet">
</head>
<body class="app header-fixed sidebar-fixed aside-menu-fixed aside-menu-hidden">
<header class="app-header navbar">
        <button class="navbar-toggler mobile-sidebar-toggler d-lg-none mr-auto" type="button">
          <span class="navbar-toggler-icon"></span>
        </button>
        <button class="navbar-toggler sidebar-toggler d-md-down-none" type="button">
          <span class="navbar-toggler-icon"></span>
        </button>
    </header>

    <div class="app-body">
      @include("layouts.sidebar")
      <main class="main">
        @yield('content')
      </main>

    </div>
    <footer class="app-footer">
    </footer>

    <script src="{{ asset('js/jquery.min.js') }}"></script>
    <script src="{{ asset('js/popper.min.js') }}"></script>
    <script src="{{ asset('js/bootstrap.min.js') }}"></script>
    <script src="{{ asset('js/pace.min.js') }}"></script>
    <script src="{{ asset('js/Chart.min.js') }}"></script>
    <script src="{{ asset('js/template.js') }}"></script>
</body>
</html>

resources/views/layouts/sidebar.blade.php
<div class="sidebar">
    <nav class="sidebar-nav">
      <ul class="nav">
        <li class="nav-item">
          <a class="nav-link active" href="#"><i class="icon-speedometer"></i> Dashbord</a>
        </li>
        <li class="nav-title">
          Menú
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#"><i class="fa fa-user"></i> Usuarios</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{{route('usuarios.create')}}"><i class="fa fa-plus"></i> Agregar Usuario</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href=""><i class="fa fa-window-close"></i> Salir </a>
        </li>
      </ul>
      </nav>
  <button class="sidebar-minimizer brand-minimizer" type="button"></button>
</div>

resources/views/usuarios/create.blade.php
@extends('layouts.app')
@section('content')
<form action="{{ route('usuarios.store') }}" method="POST" >
@csrf
  <div class="col-sm-6">
    <div class="card">
      <div class="card-header"><strong>Usuario</strong>
      <br>
      <small>Registe un nuevo usuario rellenando el formulario</small></div>
        <div class="card-body">

            <div class="form-group">
              <label for="company">RUT</label>
              <input class="form-control" id="rut" name="rut" type="text" placeholder="18415134-6">
            </div>

            <div class="form-group">
              <label for="company">Nombre</label>
              <input class="form-control" id="nombre" name="nombre" type="text" placeholder="Esteban">
            </div>

            <div class="form-group">
              <label for="company">Apellido</label>
              <input class="form-control" id="apellido" name="apellido" type="text" placeholder="Urrutia">
            </div>

            <div class="form-group">
              <label for="company">Correo</label>
              <input class="form-control" id="correo" name="correo" type="email" placeholder="Estur@gmail.com">
            </div>

            <div class="form-group">
              <label for="company">Región</label>
                {{-- {{Form::select('id_region',$regiones,null,[])}} --}}
                <select class="form-select" aria-label="Default select example" name="region" id="region" required>
                  @foreach ($regiones as $r)
                    <option value="{{$r->id}}">"{{$r->nombre}}"</option>
                  @endforeach
                </select>
            </div>

            <div class="col-6 col-sm-4 col-md-2 col-xl mb-3 mb-xl-0">
              <button class="btn btn-block btn-dark" type="submit">Enviar</button>
            </div>

        </div>
      </div>
    </div>
  </div>
</form>
@endsection

resources/views/usuarios/edit.blade.php
@extends('layouts.app')
@section('content')




@endsection

resources/views/usuarios/index.blade.php
@extends('layouts.app')
@section('content')
  <div class="container-fluid">
    <div class="card">
      <div class="card-header">
        <h2>Listado de Usuarios</h2><br/>
      </div>
      <div class="card-body">
        <table class="table table-bordered table-striped table-sm">
          <thead>
           <tr class="bg-primary">
              <th>N°</th>
              <th>Rut</th>
              <th>Nombre</th>
              <th>Correo</th>
              <th>Region</th>
              <th>Opciones </th>
            </tr>
          </thead>
          <tbody>
            @foreach ($usuarios as $usuario)
              <tr>
                <td>{{ $usuario->id }}</td>
                <td>{{ $usuario->rut }}</td>
                <td>{{ $usuario->nombre." ".$usuario->apellido }}</td>
                <td>{{ $usuario->correo }}</td>
                <td>{{ $usuario->region->nombre }}</td>
                <td>
                 <button type="button" class="btn btn-info btn-md">
                    <i class="fa fa-edit fa-2x"></i> Editar
                 </button>
                 <button type="button" class="btn btn-danger btn-md">
                    <i class="fa fa-trash fa-2x"></i> Eliminar
                 </button>
                </td>
              </tr>
            @endforeach
          </tbody>
        </table>
      </div>
    </div>
  </div>
@endsection

resources/views/usuarios/show.blade.php
@extends('layouts.app')
@section('content')




@endsection